### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by vansoftware** [vansoftware/soulmeet#1]
The first page of the app. The button at the bottom of the page simply wires the Facebook login and pulls the following information:

- Name
- Email (if available)
- Gender
- Profile Picture

Then, makes a request and sends them to the server.

**Comment by razgraf** [comment]
https://drive.google.com/open?id=0B9iGZAdQGMm7WjhOTEhKUVl3MWM


![back logo](https://cloud.githubusercontent.com/assets/15740806/20866290/8eec11f8-ba32-11e6-84c6-712bbf70114e.jpg)

**Comment by PaulRBerg** [comment]
Done. Check out the phpMyAdmin, the first user is already registered with Facebook hehe (wonder who?)
