### ISSUE TITLE
SignUp

### ISSUE THREAD

**Issue by vansoftware** [vansoftware/soulmeet#2]
Instantiated right after the Login with Facebook was successfully made. Here, the user will have to enter:

- Nationality
    - Caucasian
    - Asian
    - African
- Eye Color
    - Blue
    - Green
    - Brown
    - Black
- Interested in
    - Women
    - Men
- Interests
    - Books
    - Travelling
    - Etc (pending)

All of the information will be sent to the server and  the new created user's profile will be updated.

**Comment by PaulRBerg** [comment]
Progress:

- Server hooked up
- Networking done
- Page layout done (at least for iOS)
![simulator screen shot 10 dec 2016 13 21 38](https://cloud.githubusercontent.com/assets/8782666/21072955/9aac621a-bedb-11e6-8348-901b17006205.png)

Missing:

- UI enhancements such as toasts when data is not fully completed
- Progress Bars/ Loaders

**Comment by PaulRBerg** [comment]
Everything Done
